import { AppCard, AppCardContent, AppCardHeader, AppCardTitle } from '@/components/ui/AppCard';
import { StatusBadge } from '@/components/ui/StatusBadge';
import type { ReportDetail } from '@/modules/reports/types';

export function ReportDetailView({ report }: { report: ReportDetail }) {
  return (
    <div className="space-y-4">
      <AppCard className="p-5">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <p className="text-[11px] font-medium uppercase tracking-wide text-text-tertiary">{report.reportType} Report</p>
            <h2 className="mt-1 text-lg font-semibold text-text-primary">{report.title}</h2>
          </div>
          <StatusBadge tone="success">Ready</StatusBadge>
        </div>

        <dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-2.5 text-[12.5px] sm:grid-cols-4">
          <div>
            <dt className="text-text-tertiary">Date Range</dt>
            <dd className="text-text-primary">{report.dateRangeFrom} – {report.dateRangeTo}</dd>
          </div>
          <div>
            <dt className="text-text-tertiary">Generated By</dt>
            <dd className="text-text-primary">{report.generatedBy}</dd>
          </div>
          <div>
            <dt className="text-text-tertiary">Generated Date</dt>
            <dd className="text-text-primary">{report.generatedDate}</dd>
          </div>
          <div>
            <dt className="text-text-tertiary">Report ID</dt>
            <dd className="text-text-primary">{report.id}</dd>
          </div>
        </dl>
      </AppCard>

      <AppCard>
        <AppCardHeader><AppCardTitle>Summary</AppCardTitle></AppCardHeader>
        <AppCardContent>
          <p className="text-[12.5px] leading-relaxed text-text-secondary">{report.summary}</p>
        </AppCardContent>
      </AppCard>

      <AppCard>
        <AppCardHeader><AppCardTitle>Statistics</AppCardTitle></AppCardHeader>
        <AppCardContent className="grid grid-cols-2 gap-3 sm:grid-cols-3">
          {report.statistics.map((stat) => (
            <div key={stat.label} className="rounded-(--radius-md) border border-border-default bg-surface-raised p-3">
              <p className="text-lg font-semibold tabular-nums text-text-primary">{stat.value}</p>
              <p className="text-[11px] text-text-tertiary">{stat.label}</p>
            </div>
          ))}
        </AppCardContent>
      </AppCard>

      <AppCard>
        <AppCardHeader><AppCardTitle>Notes</AppCardTitle></AppCardHeader>
        <AppCardContent>
          <p className="text-[12.5px] text-text-secondary">{report.notes}</p>
        </AppCardContent>
      </AppCard>
    </div>
  );
}
