from __future__ import annotations

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from app.schemas.stream import StreamResponse
from app.services.camera_service import get_camera_service
from app.services.stream_service import get_stream_manager

router = APIRouter(tags=["streams"])

_MIME_TYPES = {
    ".m3u8": "application/vnd.apple.mpegurl",
    ".ts": "video/mp2t",
}


@router.get("/api/cameras/{camera_id}/stream", response_model=StreamResponse)
async def get_camera_stream(camera_id: str):
    """Ensure a stream is running for this camera (starting it if needed)
    and return the browser-facing HLS URL. Never returns the RTSP source."""
    camera_service = get_camera_service()
    stream_manager = get_stream_manager()

    camera = camera_service.get_camera(camera_id)
    if camera is None:
        raise HTTPException(status_code=404, detail=f"Unknown camera_id '{camera_id}'")

    handle = await stream_manager.ensure_stream(camera)

    return StreamResponse(
        camera_id=camera_id,
        stream_type="hls",
        stream_url=f"/api/streams/{camera_id}/index.m3u8",
        status=handle.status.value,
    )


def _validate_camera_id(camera_id: str) -> None:
    camera_service = get_camera_service()
    if not camera_service.exists(camera_id):
        raise HTTPException(status_code=404, detail=f"Unknown camera_id '{camera_id}'")


def _validate_filename(filename: str) -> None:
    """Prevent path traversal / arbitrary filesystem access. Only bare
    playlist/segment filenames generated by our own FFmpeg command are
    ever allowed - no subdirectories, no '..'."""
    suffix = "." + filename.rsplit(".", 1)[-1] if "." in filename else ""
    if (
        "/" in filename
        or "\\" in filename
        or ".." in filename
        or suffix not in _MIME_TYPES
    ):
        raise HTTPException(status_code=400, detail="Invalid stream file requested")


@router.get("/api/streams/{camera_id}/index.m3u8")
async def get_playlist(camera_id: str):
    _validate_camera_id(camera_id)
    stream_manager = get_stream_manager()
    handle = stream_manager.get_handle(camera_id)

    if handle is None or not handle.playlist_path.exists():
        raise HTTPException(
            status_code=503,
            detail="Stream not ready yet. Call GET /api/cameras/{camera_id}/stream first.",
        )

    stream_manager.touch(camera_id)
    return FileResponse(
        path=handle.playlist_path,
        media_type=_MIME_TYPES[".m3u8"],
        headers={"Cache-Control": "no-cache"},
    )


@router.get("/api/streams/{camera_id}/{segment_name}")
async def get_segment(camera_id: str, segment_name: str):
    _validate_camera_id(camera_id)
    _validate_filename(segment_name)
    stream_manager = get_stream_manager()
    handle = stream_manager.get_handle(camera_id)

    if handle is None:
        raise HTTPException(status_code=404, detail="Stream not found")

    segment_path = handle.output_dir / segment_name
    # Belt-and-braces: confirm the resolved path is still inside the
    # stream's own output directory before serving it.
    try:
        segment_path.resolve().relative_to(handle.output_dir.resolve())
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid stream file requested")

    if not segment_path.exists():
        raise HTTPException(status_code=404, detail="Segment not found")

    stream_manager.touch(camera_id)
    suffix = "." + segment_name.rsplit(".", 1)[-1]
    return FileResponse(
        path=segment_path,
        media_type=_MIME_TYPES.get(suffix, "application/octet-stream"),
        headers={"Cache-Control": "no-cache"},
    )
